# Generated by Django 5.1.7 on 2025-03-21 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billiard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('admin', models.OneToOneField(blank=True, limit_choices_to={'rol': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administra', to=settings.AUTH_USER_MODEL)),
                ('propietarios', models.ManyToManyField(limit_choices_to={'rol': 'owner'}, related_name='billares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BILLARD',
            },
        ),
    ]
