# Generated by Django 5.1.7 on 2025-03-21 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Billiard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=10)),
                ('billar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='Billiard.billiard')),
            ],
            options={
                'db_table': 'TABLE',
            },
        ),
    ]
