# Generated by Django 5.1.7 on 2025-03-21 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_acceso', models.CharField(max_length=6)),
                ('activo', models.BooleanField(default=True)),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='Table.table')),
            ],
            options={
                'db_table': 'AUTHTABLE',
            },
        ),
    ]
